name: fairmetadata4j CI

on:
  push:
  pull_request:

jobs:
  buildDeploy:
    name: Build-Deploy
    runs-on: ubuntu-latest
    
    env:
      JDK_VERSION: 11
      JDK_FILE: openjdk-11.0.2_linux-x64_bin.tar.gz
      JDK_URL: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz

    steps:
    - uses: actions/checkout@v2

    - name: Prepare JDK folder
      run: mkdir -p ~/jdk

# (1) -> Prepare cache and Java
    - name: Cache ~/.m2
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  
    - name: Cache JDK folder
      uses: actions/cache@v1
      with:
        path: ~/jdk
        key: ${{ env.JDK_FILE }}

# (2) -> Prepare Java
    - name: Download Oracle JDK
      run: |
        if [ ! -f ~/jdk/$JDK_FILE ]; then
          wget --quiet $JDK_URL -O ~/jdk/$JDK_FILE
        fi
        cp ~/jdk/$JDK_FILE .

    - name: Setup Java
      uses: actions/setup-java@master
      with:
        version: ${{ env.JDK_VERSION }}
        jdkFile: ${{ env.JDK_FILE }}

    - name: Verify Maven and Java
      run: |
        mvn --version

# (3) -> Test and build
    - name: Run tests
      run: |
        mvn --quiet -B org.jacoco:jacoco-maven-plugin:prepare-agent test

    - name: Build package
      run: |
        mvn --quiet -B --fail-fast -DskipTests package

    - name: Report coverage
      continue-on-error: true
      run: |
        mvn --quiet -B -DrepoToken=$COVERALLS_TOKEN clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report coveralls:report
        if [ $? -eq 0 ]; then
          echo "::debug::Coverage reported to Coveralls.io"
        else
          echo "::error::Failed to report coverage to Coveralls.io"
        fi
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    
# (3) -> Deploy on Nexus
    - name: Deploy (branch)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') && !contains(github.ref, 'release')
      run: |
        GITHUB_BRANCH=`echo $GITHUB_REF | cut -d/ -f3- | sed 's#/#-#g'`
        cp .nexus.settings.xml ~/.m2/settings.xml
        mvn -B deploy -DskipTests -Dchangelist=.$GITHUB_BRANCH
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    - name: Deploy (release)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        GITHUB_TAG=`echo $GITHUB_REF | cut -d/ -f3` 
        # Release vX.Y.Z
        if [[ $GITHUB_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          cp .nexus.settings.xml ~/.m2/settings.xml
          mvn -B deploy -DskipTests -Dchangelist=.RELEASE
        fi
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
